config/routes.rb
Tuna::Application.routes.draw do
  resources :icons

  resources :messages

  resources :groups_users

  resources :photos

  resources :personal_icons

  resources :favorites

  resources :articles

  resources :groups

  resources :users

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_one :message
  has_one :photo
  has_many :favorites
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render action: 'show', status: :created, location: @article }
      else
        format.html { render action: 'new' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:user_id, :group_id)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.haml
= form_for(@article) do |f|
  - if @article.errors.any?
    #error_explanation
      %h2
        = pluralize(@article.errors.count, "error")
        prohibited this article from being saved:
      %ul
        - @article.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :user_id
    %br/
    = f.number_field :user_id
  .field
    = f.label :group_id
    %br/
    = f.number_field :group_id
  .actions
    = f.submit

app/views/articles/edit.html.haml
%h1 Editing article
= render 'form'
= link_to 'Show', @article
|
\#{link_to 'Back', articles_path}

app/views/articles/index.html.haml
%h1 Listing articles
%table
  %thead
    %tr
      %th User
      %th Group
      %th
      %th
      %th
  %tbody
    - @articles.each do |article|
      %tr
        %td= article.user_id
        %td= article.group_id
        %td= link_to 'Show', article
        %td= link_to 'Edit', edit_article_path(article)
        %td= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Article', new_article_path

app/views/articles/new.html.haml
%h1 New article
= render 'form'
= link_to 'Back', articles_path

app/views/articles/show.html.haml
%p#notice= notice
%p
  %strong User:
  = @article.user_id
%p
  %strong Group:
  = @article.group_id
= link_to 'Edit', edit_article_path(@article)
|
\#{link_to 'Back', articles_path}