config/routes.rb
Tuna::Application.routes.draw do
  resources :icons

  resources :messages

  resources :groups_users

  resources :photos

  resources :personal_icons

  resources :favorites

  resources :articles

  resources :groups

  resources :users

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_and_belongs_to_many :users
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render action: 'show', status: :created, location: @group }
      else
        format.html { render action: 'new' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.haml
= form_for(@group) do |f|
  - if @group.errors.any?
    #error_explanation
      %h2
        = pluralize(@group.errors.count, "error")
        prohibited this group from being saved:
      %ul
        - @group.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .actions
    = f.submit

app/views/groups/edit.html.haml
%h1 Editing group
= render 'form'
= link_to 'Show', @group
|
\#{link_to 'Back', groups_path}

app/views/groups/index.html.haml
%h1 Listing groups
%table
  %thead
    %tr
      %th Name
      %th
      %th
      %th
  %tbody
    - @groups.each do |group|
      %tr
        %td= group.name
        %td= link_to 'Show', group
        %td= link_to 'Edit', edit_group_path(group)
        %td= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Group', new_group_path

app/views/groups/new.html.haml
%h1 New group
= render 'form'
= link_to 'Back', groups_path

app/views/groups/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @group.name
= link_to 'Edit', edit_group_path(@group)
|
\#{link_to 'Back', groups_path}