config/routes.rb
Tuna::Application.routes.draw do
  resources :icons

  resources :messages

  resources :groups_users

  resources :photos

  resources :personal_icons

  resources :favorites

  resources :articles

  resources :groups

  resources :users

end

app/models/groups_user.rb
class GroupsUser < ActiveRecord::Base
end

app/controllers/groups_users_controller.rb
class GroupsUsersController < ApplicationController
  before_action :set_groups_user, only: [:show, :edit, :update, :destroy]

  # GET /groups_users
  # GET /groups_users.json
  def index
    @groups_users = GroupsUser.all
  end

  # GET /groups_users/1
  # GET /groups_users/1.json
  def show
  end

  # GET /groups_users/new
  def new
    @groups_user = GroupsUser.new
  end

  # GET /groups_users/1/edit
  def edit
  end

  # POST /groups_users
  # POST /groups_users.json
  def create
    @groups_user = GroupsUser.new(groups_user_params)

    respond_to do |format|
      if @groups_user.save
        format.html { redirect_to @groups_user, notice: 'Groups user was successfully created.' }
        format.json { render action: 'show', status: :created, location: @groups_user }
      else
        format.html { render action: 'new' }
        format.json { render json: @groups_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups_users/1
  # PATCH/PUT /groups_users/1.json
  def update
    respond_to do |format|
      if @groups_user.update(groups_user_params)
        format.html { redirect_to @groups_user, notice: 'Groups user was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @groups_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups_users/1
  # DELETE /groups_users/1.json
  def destroy
    @groups_user.destroy
    respond_to do |format|
      format.html { redirect_to groups_users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_groups_user
      @groups_user = GroupsUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def groups_user_params
      params.require(:groups_user).permit(:group_id, :user_id)
    end
end

app/helpers/groups_users_helper.rb
module GroupsUsersHelper
end

app/views/groups_users/_form.html.haml
= form_for(@groups_user) do |f|
  - if @groups_user.errors.any?
    #error_explanation
      %h2
        = pluralize(@groups_user.errors.count, "error")
        prohibited this groups_user from being saved:
      %ul
        - @groups_user.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :group_id
    %br/
    = f.number_field :group_id
  .field
    = f.label :user_id
    %br/
    = f.number_field :user_id
  .actions
    = f.submit

app/views/groups_users/edit.html.haml
%h1 Editing groups_user
= render 'form'
= link_to 'Show', @groups_user
|
\#{link_to 'Back', groups_users_path}

app/views/groups_users/index.html.haml
%h1 Listing groups_users
%table
  %thead
    %tr
      %th Group
      %th User
      %th
      %th
      %th
  %tbody
    - @groups_users.each do |groups_user|
      %tr
        %td= groups_user.group_id
        %td= groups_user.user_id
        %td= link_to 'Show', groups_user
        %td= link_to 'Edit', edit_groups_user_path(groups_user)
        %td= link_to 'Destroy', groups_user, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Groups user', new_groups_user_path

app/views/groups_users/new.html.haml
%h1 New groups_user
= render 'form'
= link_to 'Back', groups_users_path

app/views/groups_users/show.html.haml
%p#notice= notice
%p
  %strong Group:
  = @groups_user.group_id
%p
  %strong User:
  = @groups_user.user_id
= link_to 'Edit', edit_groups_user_path(@groups_user)
|
\#{link_to 'Back', groups_users_path}