config/routes.rb
Tuna::Application.routes.draw do
  resources :icons

  resources :messages

  resources :groups_users

  resources :photos

  resources :personal_icons

  resources :favorites

  resources :articles

  resources :groups

  resources :users

end

app/models/icon.rb
class Icon < ActiveRecord::Base
  belongs_to :user
end

app/controllers/icons_controller.rb
class IconsController < ApplicationController
  before_action :set_icon, only: [:show, :edit, :update, :destroy]

  # GET /icons
  # GET /icons.json
  def index
    @icons = Icon.all
  end

  # GET /icons/1
  # GET /icons/1.json
  def show
  end

  # GET /icons/new
  def new
    @icon = Icon.new
  end

  # GET /icons/1/edit
  def edit
  end

  # POST /icons
  # POST /icons.json
  def create
    @icon = Icon.new(icon_params)

    respond_to do |format|
      if @icon.save
        format.html { redirect_to @icon, notice: 'Icon was successfully created.' }
        format.json { render action: 'show', status: :created, location: @icon }
      else
        format.html { render action: 'new' }
        format.json { render json: @icon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /icons/1
  # PATCH/PUT /icons/1.json
  def update
    respond_to do |format|
      if @icon.update(icon_params)
        format.html { redirect_to @icon, notice: 'Icon was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @icon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /icons/1
  # DELETE /icons/1.json
  def destroy
    @icon.destroy
    respond_to do |format|
      format.html { redirect_to icons_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_icon
      @icon = Icon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def icon_params
      params.require(:icon).permit(:user_id, :path)
    end
end

app/helpers/icons_helper.rb
module IconsHelper
end

app/views/icons/_form.html.haml
= form_for(@icon) do |f|
  - if @icon.errors.any?
    #error_explanation
      %h2
        = pluralize(@icon.errors.count, "error")
        prohibited this icon from being saved:
      %ul
        - @icon.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :user_id
    %br/
    = f.number_field :user_id
  .field
    = f.label :path
    %br/
    = f.text_field :path
  .actions
    = f.submit

app/views/icons/edit.html.haml
%h1 Editing icon
= render 'form'
= link_to 'Show', @icon
|
\#{link_to 'Back', icons_path}

app/views/icons/index.html.haml
%h1 Listing icons
%table
  %thead
    %tr
      %th User
      %th Path
      %th
      %th
      %th
  %tbody
    - @icons.each do |icon|
      %tr
        %td= icon.user_id
        %td= icon.path
        %td= link_to 'Show', icon
        %td= link_to 'Edit', edit_icon_path(icon)
        %td= link_to 'Destroy', icon, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Icon', new_icon_path

app/views/icons/new.html.haml
%h1 New icon
= render 'form'
= link_to 'Back', icons_path

app/views/icons/show.html.haml
%p#notice= notice
%p
  %strong User:
  = @icon.user_id
%p
  %strong Path:
  = @icon.path
= link_to 'Edit', edit_icon_path(@icon)
|
\#{link_to 'Back', icons_path}